#!/bin/sh

docker run --rm -i -h evins \
  -v $EVINS_DIR/evins_ros_docker/nodes:/root/catkin_ws/src/evins_nodes \
  -v $SIM_DIR:/root/catkin_ws/src/sim_nodes \
  -v $INST_DIR:/root/catkin_ws/ \
  -t ros:evins catkin_make -k

docker run --rm -i -h evins \
  -v $EVINS_DIR/evins_ros_docker/nodes:/root/catkin_ws/src/evins_nodes \
  -v $INST_DIR:/root/catkin_ws/ \
  -v $EVINS_DIR/evins_ros_docker/evins:/opt/evins \
  -t ros:evins bash -c "cd /opt/evins && make"
