#!/bin/sh
ID=$1
NAME=lv$ID
MISSION=$2
ROLE=$3

CMD="$@"

docker run -i --rm --name $NAME -h evins \
   -v $EVINS_DIR/evins_ros_docker/nodes:/root/catkin_ws/src/evins_nodes \
   -v $EVINS_DIR/evins_ros_docker/evins/_rel/evins:/opt/evins \
   -v $EVINS_DIR/evins_ros_docker/nodes/missions/$MISSION/etc:/opt/evins/etc \
   -v $EVINS_DIR/evins_ros_docker/nodes/missions/$MISSION/bin:/opt/bin \
   -v $SIM_DIR:/root/catkin_ws/src/sim_nodes \
   -v $INST_DIR:/root/catkin_ws/ \
   --hostname $ROLE$ID \
   -t ros:evins \
   bash -c ". /ros_entrypoint.sh && /opt/bin/run-tmux.sh $CMD"

#bash -c ". /ros_entrypoint.sh && $CMD vehicle_name:=$NAME real:=false bags:=false"

